# Einsum in Pytorch

Using this playground to learn einsum

In [3]:
import torch


In [6]:
x = torch.arange(9).reshape(3,3)
y = torch.arange(9).reshape(3,3)
x @ y

tensor([[ 15,  18,  21],
        [ 42,  54,  66],
        [ 69,  90, 111]])

In [7]:
torch.einsum("ik,kj->ij",x,y)

tensor([[ 15,  18,  21],
        [ 42,  54,  66],
        [ 69,  90, 111]])

In [14]:
print(x)
torch.einsum("ij->i",x)

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])


tensor([ 3, 12, 21])