In [2]:
!nvidia-smi


Sat Jun 15 13:34:35 2024       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 555.42.02              Driver Version: 555.42.02      CUDA Version: 12.5     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA RTX 6000 Ada Gene...    Off |   00000000:21:00.0 Off |                  Off |
| 30%   39C    P8             25W /  300W |      18MiB /  49140MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [3]:
import torch
import torch.nn as nn
import torch.nn.functional as F

In [4]:
x = torch.tensor([[[1,2,3],[4,5,6],[7,8,9]],[[1,2,3],[4,5,6],[7,8,9]],[[1,2,3],[4,5,6],[7,8,9]]],dtype=torch.float)
x.view(9,-1)

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.],
        [1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.],
        [1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

In [5]:
y = torch.arange(27,dtype=torch.float).view(3,3,3)
y

y.view(27)

loss = F.cross_entropy(x,y)
loss

tensor(100.9869)

In [9]:
a = torch.tensor([1,2,3],dtype=torch.float)
F.softmax(a)

/tmp/ipykernel_1289863/1705839279.py:2: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  F.softmax(a)


tensor([0.0900, 0.2447, 0.6652])

In [12]:
t = torch.arange(9).reshape(3,3)

In [15]:
s = torch.sum(t,dim=0)

t,s

(tensor([[0, 1, 2],
         [3, 4, 5],
         [6, 7, 8]]),
 tensor([ 9, 12, 15]))

In [16]:
s = torch.sum(t,dim=1)

t,s

(tensor([[0, 1, 2],
         [3, 4, 5],
         [6, 7, 8]]),
 tensor([ 3, 12, 21]))

In [18]:
s = torch.sum(t,dim=-1)

t,s

(tensor([[0, 1, 2],
         [3, 4, 5],
         [6, 7, 8]]),
 tensor([ 3, 12, 21]))