In [1]:
!nvidia-smi


Mon Jun 17 10:04:49 2024       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 555.42.02              Driver Version: 555.42.02      CUDA Version: 12.5     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA RTX 6000 Ada Gene...    Off |   00000000:21:00.0 Off |                  Off |
| 30%   38C    P8             25W /  300W |      15MiB /  49140MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [2]:
import torch
import torch.nn as nn
import torch.nn.functional as F

In [3]:
x = torch.tensor([[[1,2,3],[4,5,6],[7,8,9]],[[1,2,3],[4,5,6],[7,8,9]],[[1,2,3],[4,5,6],[7,8,9]]],dtype=torch.float)
x.view(9,-1)

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.],
        [1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.],
        [1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

In [4]:
y = torch.arange(27,dtype=torch.float).view(3,3,3)
y

y.view(27)

loss = F.cross_entropy(x,y)
loss

tensor(100.9869)

In [5]:
a = torch.tensor([1,2,3],dtype=torch.float)
F.softmax(a)

/tmp/ipykernel_1301495/1705839279.py:2: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  F.softmax(a)


tensor([0.0900, 0.2447, 0.6652])

In [6]:
t = torch.arange(9).reshape(3,3)

In [7]:
s = torch.sum(t,dim=0)

t,s

(tensor([[0, 1, 2],
         [3, 4, 5],
         [6, 7, 8]]),
 tensor([ 9, 12, 15]))

In [8]:
s = torch.sum(t,dim=1)

t,s

(tensor([[0, 1, 2],
         [3, 4, 5],
         [6, 7, 8]]),
 tensor([ 3, 12, 21]))

In [9]:
s = torch.sum(t,dim=-1)

t,s

(tensor([[0, 1, 2],
         [3, 4, 5],
         [6, 7, 8]]),
 tensor([ 3, 12, 21]))

In [10]:
t = torch.arange(27).reshape(3,3,3)
s = torch.sum(t,dim=0)
t,s

(tensor([[[ 0,  1,  2],
          [ 3,  4,  5],
          [ 6,  7,  8]],
 
         [[ 9, 10, 11],
          [12, 13, 14],
          [15, 16, 17]],
 
         [[18, 19, 20],
          [21, 22, 23],
          [24, 25, 26]]]),
 tensor([[27, 30, 33],
         [36, 39, 42],
         [45, 48, 51]]))

In [11]:
s = torch.sum(t,dim=1)
t,s

(tensor([[[ 0,  1,  2],
          [ 3,  4,  5],
          [ 6,  7,  8]],
 
         [[ 9, 10, 11],
          [12, 13, 14],
          [15, 16, 17]],
 
         [[18, 19, 20],
          [21, 22, 23],
          [24, 25, 26]]]),
 tensor([[ 9, 12, 15],
         [36, 39, 42],
         [63, 66, 69]]))

In [12]:
s = torch.sum(t,dim=2)
t,s

(tensor([[[ 0,  1,  2],
          [ 3,  4,  5],
          [ 6,  7,  8]],
 
         [[ 9, 10, 11],
          [12, 13, 14],
          [15, 16, 17]],
 
         [[18, 19, 20],
          [21, 22, 23],
          [24, 25, 26]]]),
 tensor([[ 3, 12, 21],
         [30, 39, 48],
         [57, 66, 75]]))

In [13]:
logits = torch.arange(4*8*65).reshape(4,8,65)

In [14]:
logits[:,-1,:].shape

torch.Size([4, 65])

In [15]:
logits[:,1,:]

tensor([[  65,   66,   67,   68,   69,   70,   71,   72,   73,   74,   75,   76,
           77,   78,   79,   80,   81,   82,   83,   84,   85,   86,   87,   88,
           89,   90,   91,   92,   93,   94,   95,   96,   97,   98,   99,  100,
          101,  102,  103,  104,  105,  106,  107,  108,  109,  110,  111,  112,
          113,  114,  115,  116,  117,  118,  119,  120,  121,  122,  123,  124,
          125,  126,  127,  128,  129],
        [ 585,  586,  587,  588,  589,  590,  591,  592,  593,  594,  595,  596,
          597,  598,  599,  600,  601,  602,  603,  604,  605,  606,  607,  608,
          609,  610,  611,  612,  613,  614,  615,  616,  617,  618,  619,  620,
          621,  622,  623,  624,  625,  626,  627,  628,  629,  630,  631,  632,
          633,  634,  635,  636,  637,  638,  639,  640,  641,  642,  643,  644,
          645,  646,  647,  648,  649],
        [1105, 1106, 1107, 1108, 1109, 1110, 1111, 1112, 1113, 1114, 1115, 1116,
         1117, 1118, 1119, 11

In [16]:
x = torch.tensor([[[1,2,3],[4,5,6],[7,8,9]],[[11,12,13],[14,15,16],[17,18,19]]])

In [17]:
x

tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]],

        [[11, 12, 13],
         [14, 15, 16],
         [17, 18, 19]]])

In [18]:
x.shape

torch.Size([2, 3, 3])

In [19]:
x[:,-1,:]

tensor([[ 7,  8,  9],
        [17, 18, 19]])

We encode batch, time and embedding

In [28]:
emb = nn.Embedding(19,4)

In [22]:
x

tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]],

        [[11, 12, 13],
         [14, 15, 16],
         [17, 18, 19]]])

In [34]:
ix = torch.tensor([1,2,3])
ix_emb = emb(ix)
ix_emb.shape

torch.Size([3, 4])

As you an see, the embedding actually you loose the real data, you will only get a vector of size embedding dimension added at each value point

In [37]:
ixx = torch.tensor([[1,2,3],[4,5,6]])
ixx_emb = emb(ixx)
ixx_emb.shape

torch.Size([2, 3, 4])

Embeddings will fail if there is no data corrosponding to the value

In [41]:
x = torch.tensor([18])
emb(x)

tensor([[-0.2205,  0.2218, -1.2863,  0.0289]], grad_fn=<EmbeddingBackward0>)

Essentially emedding adds a dimension and removes the actual data from the tensor